version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin      # Remplacez par le nom d'utilisateur souhaité
      POSTGRES_PASSWORD: adminpwd  # Remplacez par le mot de passe souhaité
      POSTGRES_DB: db   # Remplacez par le nom de la base de données souhaité
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  postgres_data:


# psql -h localhost -p 5432 -U admin -d db
# go run github.com/steebchen/prisma-client-go db push

